import { UserForm } from "./types";

export const IS_USER_DRAWER_OPENED_SEARCH_PARAM_KEY = "isUserDrawerOpened";

export const SELECTED_USER_SEARCH_PARAM_KEY = "selectedUser";

export const userFormInitialValues: UserForm = {
  address: {
    country: "",
    city: "",
    postalCode: "",
    street: "",
  },
  roles: [1],
  policies: [],
  personalInformation: {
    name: {
      first: "",
      second: "",
      third: "",
      last: "",
    },
    gender: "1",
    dateOfBirth: null,
  },
  contacts: {
    email: "",
    mobile: {
      countryCode: "+970",
      mobile: "",
    },
    emergencyMobile: {
      countryCode: "+970",
      mobile: "",
    },
  },
  userName: "",
  password: "",

  brandManufacturer: [],
  companyId: "",
};

export const countryCodes = [
  { value: "+93", label: "🇦🇫 +93 Afghanistan", flag: "🇦🇫" },
  { value: "+355", label: "🇦🇱 +355 Albania", flag: "🇦🇱" },
  { value: "+213", label: "🇩🇿 +213 Algeria", flag: "🇩🇿" },
  { value: "+376", label: "🇦🇩 +376 Andorra", flag: "🇦🇩" },
  { value: "+244", label: "🇦🇴 +244 Angola", flag: "🇦🇴" },
  { value: "+54", label: "🇦🇷 +54 Argentina", flag: "🇦🇷" },
  { value: "+374", label: "🇦🇲 +374 Armenia", flag: "🇦🇲" },
  { value: "+61", label: "🇦🇺 +61 Australia", flag: "🇦🇺" },
  { value: "+43", label: "🇦🇹 +43 Austria", flag: "🇦🇹" },
  { value: "+994", label: "🇦🇿 +994 Azerbaijan", flag: "🇦🇿" },
  { value: "+973", label: "🇧🇭 +973 Bahrain", flag: "🇧🇭" },
  { value: "+880", label: "🇧🇩 +880 Bangladesh", flag: "🇧🇩" },
  { value: "+375", label: "🇧🇾 +375 Belarus", flag: "🇧🇾" },
  { value: "+32", label: "🇧🇪 +32 Belgium", flag: "🇧🇪" },
  { value: "+501", label: "🇧🇿 +501 Belize", flag: "🇧🇿" },
  { value: "+229", label: "🇧🇯 +229 Benin", flag: "🇧🇯" },
  { value: "+975", label: "🇧🇹 +975 Bhutan", flag: "🇧🇹" },
  { value: "+591", label: "🇧🇴 +591 Bolivia", flag: "🇧🇴" },
  { value: "+387", label: "🇧🇦 +387 Bosnia and Herzegovina", flag: "🇧🇦" },
  { value: "+267", label: "🇧🇼 +267 Botswana", flag: "🇧🇼" },
  { value: "+55", label: "🇧🇷 +55 Brazil", flag: "🇧🇷" },
  { value: "+673", label: "🇧🇳 +673 Brunei", flag: "🇧🇳" },
  { value: "+359", label: "🇧🇬 +359 Bulgaria", flag: "🇧🇬" },
  { value: "+226", label: "🇧🇫 +226 Burkina Faso", flag: "🇧🇫" },
  { value: "+257", label: "🇧🇮 +257 Burundi", flag: "🇧🇮" },
  { value: "+855", label: "🇰🇭 +855 Cambodia", flag: "🇰🇭" },
  { value: "+237", label: "🇨🇲 +237 Cameroon", flag: "🇨🇲" },
  { value: "+1", label: "🇨🇦 +1 Canada", flag: "🇨🇦" },
  { value: "+238", label: "🇨🇻 +238 Cape Verde", flag: "🇨🇻" },
  { value: "+236", label: "🇨🇫 +236 Central African Republic", flag: "🇨🇫" },
  { value: "+235", label: "🇹🇩 +235 Chad", flag: "🇹🇩" },
  { value: "+56", label: "🇨🇱 +56 Chile", flag: "🇨🇱" },
  { value: "+86", label: "🇨🇳 +86 China", flag: "🇨🇳" },
  { value: "+57", label: "🇨🇴 +57 Colombia", flag: "🇨🇴" },
  { value: "+269", label: "🇰🇲 +269 Comoros", flag: "🇰🇲" },
  { value: "+242", label: "🇨🇬 +242 Congo", flag: "🇨🇬" },
  { value: "+243", label: "🇨🇩 +243 Congo, Democratic Republic", flag: "🇨🇩" },
  { value: "+506", label: "🇨🇷 +506 Costa Rica", flag: "🇨🇷" },
  { value: "+385", label: "🇭🇷 +385 Croatia", flag: "🇭🇷" },
  { value: "+53", label: "🇨🇺 +53 Cuba", flag: "🇨🇺" },
  { value: "+357", label: "🇨🇾 +357 Cyprus", flag: "🇨🇾" },
  { value: "+420", label: "🇨🇿 +420 Czech Republic", flag: "🇨🇿" },
  { value: "+45", label: "🇩🇰 +45 Denmark", flag: "🇩🇰" },
  { value: "+253", label: "🇩🇯 +253 Djibouti", flag: "🇩🇯" },
  { value: "+1 767", label: "🇩🇲 +1 767 Dominica", flag: "🇩🇲" },
  { value: "+1 809", label: "🇩🇴 +1 809 Dominican Republic", flag: "🇩🇴" },
  { value: "+593", label: "🇪🇨 +593 Ecuador", flag: "🇪🇨" },
  { value: "+20", label: "🇪🇬 +20 Egypt", flag: "🇪🇬" },
  { value: "+503", label: "🇸🇻 +503 El Salvador", flag: "🇸🇻" },
  { value: "+240", label: "🇬🇶 +240 Equatorial Guinea", flag: "🇬🇶" },
  { value: "+291", label: "🇪🇷 +291 Eritrea", flag: "🇪🇷" },
  { value: "+372", label: "🇪🇪 +372 Estonia", flag: "🇪🇪" },
  { value: "+251", label: "🇪🇹 +251 Ethiopia", flag: "🇪🇹" },
  { value: "+679", label: "🇫🇯 +679 Fiji", flag: "🇫🇯" },
  { value: "+358", label: "🇫🇮 +358 Finland", flag: "🇫🇮" },
  { value: "+33", label: "🇫🇷 +33 France", flag: "🇫🇷" },
  { value: "+241", label: "🇬🇦 +241 Gabon", flag: "🇬🇦" },
  { value: "+220", label: "🇬🇲 +220 Gambia", flag: "🇬🇲" },
  { value: "+995", label: "🇬🇪 +995 Georgia", flag: "🇬🇪" },
  { value: "+49", label: "🇩🇪 +49 Germany", flag: "🇩🇪" },
  { value: "+233", label: "🇬🇭 +233 Ghana", flag: "🇬🇭" },
  { value: "+30", label: "🇬🇷 +30 Greece", flag: "🇬🇷" },
  { value: "+299", label: "🇬🇱 +299 Greenland", flag: "🇬🇱" },
  { value: "+1 473", label: "🇬🇩 +1 473 Grenada", flag: "🇬🇩" },
  { value: "+502", label: "🇬🇹 +502 Guatemala", flag: "🇬🇹" },
  { value: "+224", label: "🇬🇳 +224 Guinea", flag: "🇬🇳" },
  { value: "+245", label: "🇬🇼 +245 Guinea-Bissau", flag: "🇬🇼" },
  { value: "+592", label: "🇬🇾 +592 Guyana", flag: "🇬🇾" },
  { value: "+509", label: "🇭🇹 +509 Haiti", flag: "🇭🇹" },
  { value: "+504", label: "🇭🇳 +504 Honduras", flag: "🇭🇳" },
  { value: "+852", label: "🇭🇰 +852 Hong Kong", flag: "🇭🇰" },
  { value: "+36", label: "🇭🇺 +36 Hungary", flag: "🇭🇺" },
  { value: "+354", label: "🇮🇸 +354 Iceland", flag: "🇮🇸" },
  { value: "+91", label: "🇮🇳 +91 India", flag: "🇮🇳" },
  { value: "+62", label: "🇮🇩 +62 Indonesia", flag: "🇮🇩" },
  { value: "+98", label: "🇮🇷 +98 Iran", flag: "🇮🇷" },
  { value: "+964", label: "🇮🇶 +964 Iraq", flag: "🇮🇶" },
  { value: "+353", label: "🇮🇪 +353 Ireland", flag: "🇮🇪" },
  { value: "+972", label: "🇮🇱 +972 Israel", flag: "🇮🇱" },
  { value: "+39", label: "🇮🇹 +39 Italy", flag: "🇮🇹" },
  { value: "+225", label: "🇨🇮 +225 Ivory Coast", flag: "🇨🇮" },
  { value: "+1 876", label: "🇯🇲 +1 876 Jamaica", flag: "🇯🇲" },
  { value: "+81", label: "🇯🇵 +81 Japan", flag: "🇯🇵" },
  { value: "+962", label: "🇯🇴 +962 Jordan", flag: "🇯🇴" },
  { value: "+7", label: "🇰🇿 +7 Kazakhstan", flag: "🇰🇿" },
  { value: "+254", label: "🇰🇪 +254 Kenya", flag: "🇰🇪" },
  { value: "+686", label: "🇰🇮 +686 Kiribati", flag: "🇰🇮" },
  { value: "+965", label: "🇰🇼 +965 Kuwait", flag: "🇰🇼" },
  { value: "+996", label: "🇰🇬 +996 Kyrgyzstan", flag: "🇰🇬" },
  { value: "+856", label: "🇱🇦 +856 Laos", flag: "🇱🇦" },
  { value: "+371", label: "🇱🇻 +371 Latvia", flag: "🇱🇻" },
  { value: "+961", label: "🇱🇧 +961 Lebanon", flag: "🇱🇧" },
  { value: "+266", label: "🇱🇸 +266 Lesotho", flag: "🇱🇸" },
  { value: "+231", label: "🇱🇷 +231 Liberia", flag: "🇱🇷" },
  { value: "+218", label: "🇱🇾 +218 Libya", flag: "🇱🇾" },
  { value: "+423", label: "🇱🇮 +423 Liechtenstein", flag: "🇱🇮" },
  { value: "+370", label: "🇱🇹 +370 Lithuania", flag: "🇱🇹" },
  { value: "+352", label: "🇱🇺 +352 Luxembourg", flag: "🇱🇺" },
  { value: "+853", label: "🇲🇴 +853 Macao", flag: "🇲🇴" },
  { value: "+389", label: "🇲🇰 +389 Macedonia", flag: "🇲🇰" },
  { value: "+261", label: "🇲🇬 +261 Madagascar", flag: "🇲🇬" },
  { value: "+265", label: "🇲🇼 +265 Malawi", flag: "🇲🇼" },
  { value: "+60", label: "🇲🇾 +60 Malaysia", flag: "🇲🇾" },
  { value: "+960", label: "🇲🇻 +960 Maldives", flag: "🇲🇻" },
  { value: "+223", label: "🇲🇱 +223 Mali", flag: "🇲🇱" },
  { value: "+356", label: "🇲🇹 +356 Malta", flag: "🇲🇹" },
  { value: "+692", label: "🇲🇭 +692 Marshall Islands", flag: "🇲🇭" },
  { value: "+222", label: "🇲🇷 +222 Mauritania", flag: "🇲🇷" },
  { value: "+230", label: "🇲🇺 +230 Mauritius", flag: "🇲🇺" },
  { value: "+52", label: "🇲🇽 +52 Mexico", flag: "🇲🇽" },
  { value: "+691", label: "🇫🇲 +691 Micronesia", flag: "🇫🇲" },
  { value: "+373", label: "🇲🇩 +373 Moldova", flag: "🇲🇩" },
  { value: "+377", label: "🇲🇨 +377 Monaco", flag: "🇲🇨" },
  { value: "+976", label: "🇲🇳 +976 Mongolia", flag: "🇲🇳" },
  { value: "+382", label: "🇲🇪 +382 Montenegro", flag: "🇲🇪" },
  { value: "+212", label: "🇲🇦 +212 Morocco", flag: "🇲🇦" },
  { value: "+258", label: "🇲🇿 +258 Mozambique", flag: "🇲🇿" },
  { value: "+95", label: "🇲🇲 +95 Myanmar", flag: "🇲🇲" },
  { value: "+264", label: "🇳🇦 +264 Namibia", flag: "🇳🇦" },
  { value: "+674", label: "🇳🇷 +674 Nauru", flag: "🇳🇷" },
  { value: "+977", label: "🇳🇵 +977 Nepal", flag: "🇳🇵" },
  { value: "+31", label: "🇳🇱 +31 Netherlands", flag: "🇳🇱" },
  { value: "+64", label: "🇳🇿 +64 New Zealand", flag: "🇳🇿" },
  { value: "+505", label: "🇳🇮 +505 Nicaragua", flag: "🇳🇮" },
  { value: "+227", label: "🇳🇪 +227 Niger", flag: "🇳🇪" },
  { value: "+234", label: "🇳🇬 +234 Nigeria", flag: "🇳🇬" },
  { value: "+47", label: "🇳🇴 +47 Norway", flag: "🇳🇴" },
  { value: "+968", label: "🇴🇲 +968 Oman", flag: "🇴🇲" },
  { value: "+92", label: "🇵🇰 +92 Pakistan", flag: "🇵🇰" },
  { value: "+680", label: "🇵🇼 +680 Palau", flag: "🇵🇼" },
  { value: "+970", label: "🇵🇸 +970 Palestine", flag: "🇵🇸" },
  { value: "+507", label: "🇵🇦 +507 Panama", flag: "🇵🇦" },
  { value: "+675", label: "🇵🇬 +675 Papua New Guinea", flag: "🇵🇬" },
  { value: "+595", label: "🇵🇾 +595 Paraguay", flag: "🇵🇾" },
  { value: "+51", label: "🇵🇪 +51 Peru", flag: "🇵🇪" },
  { value: "+63", label: "🇵🇭 +63 Philippines", flag: "🇵🇭" },
  { value: "+48", label: "🇵🇱 +48 Poland", flag: "🇵🇱" },
  { value: "+351", label: "🇵🇹 +351 Portugal", flag: "🇵🇹" },
  { value: "+974", label: "🇶🇦 +974 Qatar", flag: "🇶🇦" },
  { value: "+40", label: "🇷🇴 +40 Romania", flag: "🇷🇴" },
  { value: "+250", label: "🇷🇼 +250 Rwanda", flag: "🇷🇼" },
  { value: "+290", label: "🇸🇭 +290 Saint Helena", flag: "🇸🇭" },
  { value: "+1 869", label: "🇰🇳 +1 869 Saint Kitts and Nevis", flag: "🇰🇳" },
  { value: "+1 758", label: "🇱🇨 +1 758 Saint Lucia", flag: "🇱🇨" },
  { value: "+590", label: "🇲🇫 +590 Saint Martin", flag: "🇲🇫" },
  { value: "+508", label: "🇵🇲 +508 Saint Pierre and Miquelon", flag: "🇵🇲" },
  {
    value: "+1 784",
    label: "🇻🇨 +1 784 Saint Vincent and the Grenadines",
    flag: "🇻🇨",
  },
  { value: "+685", label: "🇼🇸 +685 Samoa", flag: "🇼🇸" },
  { value: "+378", label: "🇸🇲 +378 San Marino", flag: "🇸🇲" },
  { value: "+239", label: "🇸🇹 +239 Sao Tome and Principe", flag: "🇸🇹" },
  { value: "+966", label: "🇸🇦 +966 Saudi Arabia", flag: "🇸🇦" },
  { value: "+221", label: "🇸🇳 +221 Senegal", flag: "🇸🇳" },
  { value: "+381", label: "🇷🇸 +381 Serbia", flag: "🇷🇸" },
  { value: "+248", label: "🇸🇨 +248 Seychelles", flag: "🇸🇨" },
  { value: "+232", label: "🇸🇱 +232 Sierra Leone", flag: "🇸🇱" },
  { value: "+65", label: "🇸🇬 +65 Singapore", flag: "🇸🇬" },
  { value: "+421", label: "🇸🇰 +421 Slovakia", flag: "🇸🇰" },
  { value: "+386", label: "🇸🇮 +386 Slovenia", flag: "🇸🇮" },
  { value: "+677", label: "🇸🇧 +677 Solomon Islands", flag: "🇸🇧" },
  { value: "+252", label: "🇸🇴 +252 Somalia", flag: "🇸🇴" },
  { value: "+27", label: "🇿🇦 +27 South Africa", flag: "🇿🇦" },
  { value: "+82", label: "🇰🇷 +82 South Korea", flag: "🇰🇷" },
  { value: "+211", label: "🇸🇸 +211 South Sudan", flag: "🇸🇸" },
  { value: "+34", label: "🇪🇸 +34 Spain", flag: "🇪🇸" },
  { value: "+94", label: "🇱🇰 +94 Sri Lanka", flag: "🇱🇰" },
  { value: "+249", label: "🇸🇩 +249 Sudan", flag: "🇸🇩" },
  { value: "+597", label: "🇸🇷 +597 Suriname", flag: "🇸🇷" },
  { value: "+268", label: "🇸🇿 +268 Eswatini", flag: "🇸🇿" },
  { value: "+46", label: "🇸🇪 +46 Sweden", flag: "🇸🇪" },
  { value: "+41", label: "🇨🇭 +41 Switzerland", flag: "🇨🇭" },
  { value: "+963", label: "🇸🇾 +963 Syria", flag: "🇸🇾" },
  { value: "+886", label: "🇹🇼 +886 Taiwan", flag: "🇹🇼" },
  { value: "+992", label: "🇹🇯 +992 Tajikistan", flag: "🇹🇯" },
  { value: "+255", label: "🇹🇿 +255 Tanzania", flag: "🇹🇿" },
  { value: "+66", label: "🇹🇭 +66 Thailand", flag: "🇹🇭" },
  { value: "+670", label: "🇹🇱 +670 Timor-Leste", flag: "🇹🇱" },
  { value: "+228", label: "🇹🇬 +228 Togo", flag: "🇹🇬" },
  { value: "+690", label: "🇹🇰 +690 Tokelau", flag: "🇹🇰" },
  { value: "+676", label: "🇹🇴 +676 Tonga", flag: "🇹🇴" },
  { value: "+1 868", label: "🇹🇹 +1 868 Trinidad and Tobago", flag: "🇹🇹" },
  { value: "+216", label: "🇹🇳 +216 Tunisia", flag: "🇹🇳" },
  { value: "+90", label: "🇹🇷 +90 Turkey", flag: "🇹🇷" },
  { value: "+993", label: "🇹🇲 +993 Turkmenistan", flag: "🇹🇲" },
  { value: "+688", label: "🇹🇻 +688 Tuvalu", flag: "🇹🇻" },
  { value: "+256", label: "🇺🇬 +256 Uganda", flag: "🇺🇬" },
  { value: "+380", label: "🇺🇦 +380 Ukraine", flag: "🇺🇦" },
  { value: "+971", label: "🇦🇪 +971 United Arab Emirates", flag: "🇦🇪" },
  { value: "+44", label: "🇬🇧 +44 United Kingdom", flag: "🇬🇧" },
  { value: "+598", label: "🇺🇾 +598 Uruguay", flag: "🇺🇾" },
  { value: "+998", label: "🇺🇿 +998 Uzbekistan", flag: "🇺🇿" },
  { value: "+678", label: "🇻🇺 +678 Vanuatu", flag: "🇻🇺" },
  { value: "+58", label: "🇻🇪 +58 Venezuela", flag: "🇻🇪" },
  { value: "+84", label: "🇻🇳 +84 Vietnam", flag: "🇻🇳" },
  { value: "+681", label: "🇼🇫 +681 Wallis and Futuna", flag: "🇼🇫" },
  { value: "+967", label: "🇾🇪 +967 Yemen", flag: "🇾🇪" },
  { value: "+260", label: "🇿🇲 +260 Zambia", flag: "🇿🇲" },
  { value: "+263", label: "🇿🇼 +263 Zimbabwe", flag: "🇿🇼" },
];
