import { Admin, Employee, Manager, User } from "@/types/user";

export const users: User[] = [
  {
    id: "1",
    avatar:
      "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-1.png",
    fullName: "Robert Wolfkisser",
    job: "Logistics Engineer",
    email: "rob_wolf@gmail.com",
    phoneNumber: "+970 (598) 886 09 12",
  },
  {
    id: "2",
    avatar:
      "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-7.png",
    fullName: "Jill Jailbreaker",
    job: "Customs Broker",
    email: "jj@breaker.com",
    phoneNumber: "+970 (598) 777 12 76",
  },
  {
    id: "3",
    avatar:
      "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-2.png",
    fullName: "Henry Silkeater",
    job: "Inventory Control Specialist",
    email: "henry@silkeater.io",
    phoneNumber: "+970 (598) 384 88 34",
  },
  {
    id: "4",
    avatar:
      "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-3.png",
    fullName: "Bill Horsefighter",
    job: "Supply Chain Analyst",
    email: "bhorsefighter@gmail.com",
    phoneNumber: "+970 (598) 341 45 22",
  },
  {
    id: "5",
    avatar:
      "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/avatars/avatar-10.png",
    fullName: "Jeremy Footviewer",
    job: "Transportation Manager",
    email: "jeremy@foot.dev",
    phoneNumber: "+970 (598) 245 65 65",
  },
];

export const admins: Admin[] = [
  {
    id: "1",
    username: "adminTech",
    password: "securepass123",
    email: "admin@logi.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "3",
    username: "adminHealth",
    password: "securepass789",
    email: "admin@healthsolutions.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "5",
    username: "adminFinance",
    password: "securepass111",
    email: "admin@financeexperts.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "7",
    username: "adminEducation",
    password: "securepass333",
    email: "admin@educationfirst.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "9",
    username: "adminRetail",
    password: "securepass555",
    email: "admin@retailworld.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "11",
    username: "adminFood",
    password: "securepass777",
    email: "admin@foodiesdelight.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "13",
    username: "adminTravel",
    password: "securepass999",
    email: "admin@travelexperts.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "15",
    username: "adminGreen",
    password: "securepass1111",
    email: "admin@greenenergy.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "17",
    username: "adminPioneers",
    password: "securepass3333",
    email: "admin@techpioneers.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "19",
    username: "adminMarketing",
    password: "securepass5555",
    email: "admin@marketingmasters.com",
    role: "Admin",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
];

export const managers: Manager[] = [
  {
    id: "2",
    username: "managerTech",
    password: "securepass456",
    email: "manager@logi.com",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "4",
    username: "managerHealth",
    password: "securepass101",
    email: "manager@healthsolutions.com",
    departmentName: "Healthcare Services",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "20",
    username: "managerMarketing",
    password: "securepass6666",
    email: "manager@marketingmasters.com",
    departmentName: "Digital Marketing",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "18",
    username: "managerPioneers",
    password: "securepass4444",
    email: "manager@techpioneers.com",
    departmentName: "Product Development",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "16",
    username: "managerGreen",
    password: "securepass2222",
    email: "manager@greenenergy.com",
    departmentName: "Engineering",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "12",
    username: "managerFood",
    password: "securepass888",
    email: "manager@foodiesdelight.com",
    departmentName: "Culinary",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "8",
    username: "managerEducation",
    password: "securepass444",
    email: "manager@educationfirst.com",
    departmentName: "Student Services",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "6",
    username: "managerFinance",
    password: "securepass222",
    email: "manager@financeexperts.com",
    departmentName: "Consulting",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "10",
    username: "managerRetail",
    password: "securepass666",
    email: "manager@retailworld.com",
    departmentName: "Store Operations",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
  {
    id: "14",
    username: "managerTravel",
    password: "securepass000",
    email: "manager@travelexperts.com",
    departmentName: "Travel Services",
    createdAt: "2022-01-01",
    updatedAt: "2022-06-01",
  },
];

export const employees: Employee[] = [
  { id: 1, firstName: "Alice", lastName: "Johnson", position: "Developer" },
  { id: 2, firstName: "Bob", lastName: "Smith", position: "Designer" },
  { id: 3, firstName: "Carol", lastName: "White", position: "Nurse" },
  { id: 4, firstName: "David", lastName: "Green", position: "Doctor" },
  { id: 5, firstName: "Eve", lastName: "Brown", position: "Accountant" },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Black",
    position: "Financial Analyst",
  },
  { id: 7, firstName: "Grace", lastName: "Adams", position: "Teacher" },
  { id: 8, firstName: "Henry", lastName: "Evans", position: "Counselor" },
  {
    id: 9,
    firstName: "Ivy",
    lastName: "Brown",
    position: "Sales Associate",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Wilson",
    position: "Store Manager",
  },
  { id: 11, firstName: "Kim", lastName: "Taylor", position: "Chef" },
  { id: 12, firstName: "Leo", lastName: "Martinez", position: "Waiter" },
  {
    id: 13,
    firstName: "Mia",
    lastName: "Johnson",
    position: "Travel Agent",
  },
  {
    id: 14,
    firstName: "Nina",
    lastName: "Williams",
    position: "Tour Guide",
  },
  { id: 15, firstName: "Oliver", lastName: "Brown", position: "Engineer" },
  { id: 16, firstName: "Paula", lastName: "Jones", position: "Technician" },
  {
    id: 17,
    firstName: "Quinn",
    lastName: "Stevens",
    position: "Developer",
  },
  { id: 18, firstName: "Ryan", lastName: "White", position: "UX Designer" },
  {
    id: 19,
    firstName: "Sara",
    lastName: "Lee",
    position: "Marketing Specialist",
  },
  { id: 20, firstName: "Tom", lastName: "Young", position: "SEO Expert" },
];
